name: '19'
timestamp: 1528235340
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions:
  breadcrumbs: breadcrumbs
  sidebar: sidebar
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-4206: 'Logo / Image'
    logo-9938: 'Logo / Image'
  menu:
    menu-9682: Menu
  bloglayoutSZ:
    bloglayoutSZ-9204: 'Blog layout - list'
    bloglayoutSZ-9166: 'Blog layout - default'
  spacer:
    spacer-4815: Spacer
    spacer-5006: Spacer
  module:
    position-module-9437: 'newsflash vertical'
    position-module-5305: 'newsflash default'
    position-module-9421: articles-category
    position-module-6937: 'newsflash horizontal'
    position-module-3469: 'latest articles'
  messages:
    system-messages-9625: 'System Messages'
  position:
    position-position-1064: breadcrumbs
    position-position-5140: sidebar
  content:
    system-content-8244: 'Page Content'
  copyright:
    copyright-4883: Copyright
  horizontalmenu:
    horizontalmenu-5587: 'Horizontal Menu'
  totop:
    totop-7381: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-8414: 'Social Floating'
  mobile-menu:
    mobile-menu-1882: Mobile-menu
inherit:
  default:
    zenith: zenith
    navtop: navtop
    navigation: navigation
    logo-4206: logo-9501
    menu-9682: menu-6609
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    spacer-4815: spacer-2395
    system-messages-9625: system-messages-2617
    system-content-8244: system-content-1966
    spacer-5006: spacer-4623
    position-position-5140: position-position-3512
    mainbottom: mainbottom
    footertop: footertop
    footer: footer
    logo-9938: logo-9571
    copyright-4883: copyright-1736
    horizontalmenu-5587: horizontalmenu-9034
    totop-7381: totop-8670
    socialfloatingSZ-8414: socialfloatingSZ-2700
    footerbottom: footerbottom
    nadir: nadir
    offcanvas: offcanvas
    mobile-menu-1882: mobile-menu-5697
