name: 19
timestamp: 1531578806
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  portfolioSZ:
    portfolioSZ-6254: Portfolio
  logo:
    logo-4206: 'Logo / Image'
    logo-9938: 'Logo / Image'
  menu:
    menu-9682: Menu
  spacer:
    spacer-4815: Spacer
    spacer-5006: Spacer
  messages:
    system-messages-9625: 'System Messages'
  module:
    position-module-1104: 'articles category grouped'
    position-module-1008: latest-articles
  content:
    system-content-8244: 'Page Content'
  copyright:
    copyright-4883: Copyright
  horizontalmenu:
    horizontalmenu-5587: 'Horizontal Menu'
  totop:
    totop-7381: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-8414: 'Social Floating'
  mobile-menu:
    mobile-menu-1882: Mobile-menu
inherit:
  default:
    zenith: zenith
    navtop: navtop
    navigation: navigation
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    mainbottom: mainbottom
    footertop: footertop
    footer: footer
    footerbottom: footerbottom
    nadir: nadir
    offcanvas: offcanvas
    logo-4206: logo-9501
    menu-9682: menu-6609
    spacer-4815: spacer-2395
    system-messages-9625: system-messages-2617
    position-module-1104: position-module-9693
    system-content-8244: system-content-1966
    spacer-5006: spacer-4623
    position-module-1008: position-module-8967
    logo-9938: logo-9571
    copyright-4883: copyright-1736
    horizontalmenu-5587: horizontalmenu-9034
    totop-7381: totop-8670
    socialfloatingSZ-8414: socialfloatingSZ-2700
    mobile-menu-1882: mobile-menu-5697
