name: '16'
timestamp: 1531695625
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1529047451
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9501: 'Logo / Image'
    logo-9571: 'Logo / Image'
  menu:
    menu-6609: Menu
  spacer:
    spacer-2395: Spacer
    spacer-4623: Spacer
  messages:
    system-messages-2617: 'System Messages'
  copyright:
    copyright-1736: Copyright
  horizontalmenu:
    horizontalmenu-9034: 'Horizontal Menu'
  totop:
    totop-8670: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-2700: 'Social Floating'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
inherit: {  }
