preset: preset1
accent:
  color-1: '#e31c3d'
zenith:
  section-preset: disabled
navtop:
  section-preset: accent2
intro:
  section-preset: accent2
features:
  section-preset: accent2
  text-color: '#ffffff'
expanded:
  text-color: '#ffffff'
mainbottom:
  section-preset: accent2
footertop:
  section-preset: accent2
footerbottom:
  section-preset: accent2
nadir:
  link-color: '#0071bc'
offcanvas:
  background: '#0071bc'
  toggle-color: '#ffffff'
