name: 32
timestamp: 1495993965
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1486942597
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  spacer:
    spacer-3728: Spacer
    spacer-8068: Spacer
  module:
    position-module-3439: 'newsflash vertical'
    position-module-8366: 'newsflash default'
    position-module-2384: 'articles category grouped'
    position-module-5533: 'latest articles'
    position-module-8407: 'newsflash horizontal'
  messages:
    system-messages-3125: 'System Messages'
  content:
    system-content-7513: 'Page Content'
  logo:
    logo-1906: 'Logo / Image'
    logo-6707: 'Logo / Image'
  menu:
    menu-3721: Menu
  customcontentSZ:
    customcontentSZ-4952: 'Custom Content'
  copyright:
    copyright-4037: Copyright
  horizontalmenu:
    horizontalmenu-4629: 'Horizontal Menu'
  totop:
    totop-8519: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-6950: 'Social Floating'
  mobile-menu:
    mobile-menu-2190: Mobile-menu
inherit:
  default:
    zenith: zenith
    navtop: navtop
    navigation: navigation
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    spacer-3728: spacer-2395
    system-messages-3125: system-messages-2617
    system-content-7513: system-content-1966
    spacer-8068: spacer-4623
    footertop: footertop
    footer: footer
    footerbottom: footerbottom
    nadir: nadir
    offcanvas: offcanvas
    logo-1906: logo-9501
    menu-3721: menu-6609
    customcontentSZ-4952: customcontentSZ-5107
    logo-6707: logo-9571
    copyright-4037: copyright-1736
    horizontalmenu-4629: horizontalmenu-9034
    totop-8519: totop-8670
    socialfloatingSZ-6950: socialfloatingSZ-2700
    mobile-menu-2190: mobile-menu-5697
