version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1486942597
layout:
  zenith: {  }
  navtop: {  }
  navigation: {  }
  header: {  }
  intro: {  }
  features: {  }
  utility: {  }
  above: {  }
  testimonials: {  }
  expanded: {  }
  /container-main/:
    -
      -
        'aside 25':
          -
            - spacer-3728
          -
            - position-module-3439
      -
        'mainbar 50':
          -
            - system-messages-3125
          -
            - position-module-8366
          -
            - position-module-2384
          -
            - system-content-7513
      -
        'sidebar 25':
          -
            - spacer-8068
          -
            - position-module-5533
  /mainbottom/:
    -
      - position-module-8407
  footertop: {  }
  footer: {  }
  footerbottom: {  }
  nadir: {  }
  offcanvas: {  }
structure:
  zenith:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  navtop:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  header:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  intro:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  features:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  testimonials:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  expanded:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  aside:
    attributes:
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: ''
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
    attributes:
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: ''
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  mainbottom:
    type: section
    attributes:
      boxed: ''
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: ''
  footertop:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  footerbottom:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  nadir:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
content:
  spacer-3728:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: spacer-2395
  position-module-3439:
    title: 'newsflash vertical'
    attributes:
      module_id: '106'
      key: newsflash-vertical
  system-messages-3125:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: system-messages-2617
  position-module-8366:
    title: 'newsflash default'
    attributes:
      module_id: '104'
      key: newsflash-default
  position-module-2384:
    title: 'articles category grouped'
    attributes:
      module_id: '107'
  system-content-7513:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: system-content-1966
  spacer-8068:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: spacer-4623
  position-module-5533:
    title: 'latest articles'
    attributes:
      module_id: '108'
      key: latest-articles
  position-module-8407:
    title: 'newsflash horizontal'
    attributes:
      module_id: '105'
      key: newsflash-horizontal
