name: 17
timestamp: 1531578806
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  customcontentSZ:
    customcontentSZ-7379: 'Custom Content'
  logo:
    logo-9700: 'Logo / Image'
    logo-1745: 'Logo / Image'
  menu:
    menu-3863: Menu
  spacer:
    spacer-2355: Spacer
    spacer-3075: Spacer
  messages:
    system-messages-1764: 'System Messages'
  module:
    position-module-8970: 'articles category grouped'
    position-module-9006: latest-articles
  content:
    system-content-4217: 'Page Content'
  copyright:
    copyright-9961: Copyright
  horizontalmenu:
    horizontalmenu-6578: 'Horizontal Menu'
  totop:
    totop-7087: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-9606: 'Social Floating'
  mobile-menu:
    mobile-menu-3312: Mobile-menu
inherit:
  default:
    zenith: zenith
    navtop: navtop
    navigation: navigation
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    mainbottom: mainbottom
    footertop: footertop
    footer: footer
    footerbottom: footerbottom
    nadir: nadir
    offcanvas: offcanvas
    logo-9700: logo-9501
    menu-3863: menu-6609
    spacer-2355: spacer-2395
    system-messages-1764: system-messages-2617
    position-module-8970: position-module-9693
    system-content-4217: system-content-1966
    spacer-3075: spacer-4623
    position-module-9006: position-module-8967
    logo-1745: logo-9571
    copyright-9961: copyright-1736
    horizontalmenu-6578: horizontalmenu-9034
    totop-7087: totop-8670
    socialfloatingSZ-9606: socialfloatingSZ-2700
    mobile-menu-3312: mobile-menu-5697
