name: '17'
timestamp: 1529013746
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9700: 'Logo / Image'
    logo-1745: 'Logo / Image'
  menu:
    menu-3863: Menu
  featuredarticlesSZ:
    featuredarticlesSZ-9554: 'Featured Articles'
  spacer:
    spacer-2355: Spacer
    spacer-3075: Spacer
  messages:
    system-messages-1764: 'System Messages'
  content:
    system-content-5957: 'Page Content'
  module:
    position-module-9006: latest-articles
  copyright:
    copyright-9961: Copyright
  horizontalmenu:
    horizontalmenu-6578: 'Horizontal Menu'
  totop:
    totop-7087: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-9606: 'Social Floating'
  mobile-menu:
    mobile-menu-3312: Mobile-menu
inherit:
  default:
    zenith: zenith
    navtop: navtop
    navigation: navigation
    logo-9700: logo-9501
    menu-3863: menu-6609
    header: header
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    spacer-2355: spacer-2395
    system-messages-1764: system-messages-2617
    sidebar: sidebar
    spacer-3075: spacer-4623
    position-module-9006: position-module-8967
    mainbottom: mainbottom
    footertop: footertop
    footer: footer
    logo-1745: logo-9571
    copyright-9961: copyright-1736
    horizontalmenu-6578: horizontalmenu-9034
    totop-7087: totop-8670
    socialfloatingSZ-9606: socialfloatingSZ-2700
    footerbottom: footerbottom
    nadir: nadir
    offcanvas: offcanvas
    mobile-menu-3312: mobile-menu-5697
