version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
layout:
  zenith: {  }
  navtop: {  }
  navigation: {  }
  header: {  }
  /intro/:
    -
      - toppostsSZ-9977
  features: {  }
  utility: {  }
  above: {  }
  testimonials: {  }
  expanded: {  }
  /container-main/:
    -
      -
        'aside 25':
          -
            - spacer-2355
      -
        'mainbar 50':
          -
            - system-messages-1764
          -
            - system-content-5957
      -
        'sidebar 25': {  }
  mainbottom: {  }
  footertop: {  }
  footer: {  }
  footerbottom: {  }
  nadir: {  }
  offcanvas: {  }
structure:
  zenith:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  navtop:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  header:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  intro:
    type: section
    attributes:
      boxed: '0'
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: ''
  features:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  testimonials:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  expanded:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  aside:
    attributes:
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: ''
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
    attributes:
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: ''
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  mainbottom:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  footertop:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  footerbottom:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  nadir:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
content:
  toppostsSZ-9977:
    title: 'Top Posts'
    attributes:
      layout: top5_1+4
      article:
        filter:
          categories: ''
          articles: ''
          featured: include
        limit:
          total: '5'
          start: '0'
        sort:
          orderby: publish_up
          ordering: ASC
        display:
          title:
            limit: '40'
  spacer-2355:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: spacer-2395
  system-messages-1764:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: system-messages-2617
