name: '22'
timestamp: 1531696564
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-8132: 'Logo / Image'
    logo-7999: 'Logo / Image'
  menu:
    menu-5346: Menu
  timelineSZ:
    timelineSZ-9781: Timeline
  spacer:
    spacer-2633: Spacer
    spacer-9387: Spacer
  messages:
    system-messages-2013: 'System Messages'
  module:
    position-module-9315: 'articles category grouped'
    position-module-9244: latest-articles
  content:
    system-content-9853: 'Page Content'
  copyright:
    copyright-5101: Copyright
  horizontalmenu:
    horizontalmenu-1052: 'Horizontal Menu'
  totop:
    totop-4150: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-9635: 'Social Floating'
  mobile-menu:
    mobile-menu-3101: Mobile-menu
inherit:
  default:
    zenith: zenith
    navtop: navtop
    navigation: navigation
    logo-8132: logo-9501
    menu-5346: menu-6609
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    spacer-2633: spacer-2395
    mainbar: mainbar
    system-messages-2013: system-messages-2617
    position-module-9315: position-module-9693
    system-content-9853: system-content-1966
    sidebar: sidebar
    spacer-9387: spacer-4623
    position-module-9244: position-module-8967
    mainbottom: mainbottom
    footertop: footertop
    footer: footer
    logo-7999: logo-9571
    copyright-5101: copyright-1736
    horizontalmenu-1052: horizontalmenu-9034
    totop-4150: totop-8670
    socialfloatingSZ-9635: socialfloatingSZ-2700
    footerbottom: footerbottom
    nadir: nadir
    offcanvas: offcanvas
    mobile-menu-3101: mobile-menu-5697
