name: 22
timestamp: 1495993965
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  customcontentSZ:
    customcontentSZ-7273: 'Custom Content'
  custom:
    custom-4289: TITLE
    custom-3019: 'Custom HTML'
    custom-5222: TITLE
    custom-2957: 'Custom HTML'
  imagegallerySZ:
    imagegallerySZ-1112: 'Image Gallery'
    imagegallerySZ-3432: 'Image Gallery'
    imagegallerySZ-7872: 'Image Gallery'
  owlcarousel:
    owlcarousel-3755: 'Owl Carousel'
  contenttabs:
    contenttabs-1443: 'Content Tabs'
  contentcubes:
    contentcubes-8252: 'Content Cubes'
  testimonialSZ:
    testimonialSZ-7910: Testimonials
    testimonialSZ-5460: Testimonials
  pricetableSZ:
    pricetableSZ-6249: 'Price Table'
  logo:
    logo-2939: 'Logo / Image'
    logo-8132: 'Logo / Image'
  copyright:
    copyright-7645: Copyright
  horizontalmenu:
    horizontalmenu-8827: 'Horizontal Menu'
  totop:
    totop-4095: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-8612: 'Social Floating'
  mobile-menu:
    mobile-menu-2618: Mobile-menu
  menu:
    menu-5346: Menu
inherit:
  10:
    zenith: zenith
    navtop: navtop
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    mainbottom: mainbottom
    footertop: footertop
    footer: footer
    footerbottom: footerbottom
    nadir: nadir
    offcanvas: offcanvas
    customcontentSZ-7273: customcontentSZ-5107
    custom-4289: custom-8642
    imagegallerySZ-1112: imagegallerySZ-3581
    imagegallerySZ-3432: imagegallerySZ-3358
    imagegallerySZ-7872: imagegallerySZ-3171
    owlcarousel-3755: owlcarousel-2455
    contenttabs-1443: contenttabs-6250
    custom-3019: custom-1615
    contentcubes-8252: contentcubes-7850
    custom-5222: custom-4995
    testimonialSZ-7910: testimonialSZ-3654
    testimonialSZ-5460: testimonialSZ-9046
    custom-2957: custom-1476
    pricetableSZ-6249: pricetableSZ-8713
    logo-2939: logo-9571
    copyright-7645: copyright-1736
    horizontalmenu-8827: horizontalmenu-9034
    totop-4095: totop-8670
    socialfloatingSZ-8612: socialfloatingSZ-2700
    mobile-menu-2618: mobile-menu-5697
  default:
    navigation: navigation
    logo-8132: logo-9501
    menu-5346: menu-6609
