name: 25
timestamp: 1495993965
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  customcontentSZ:
    customcontentSZ-5107: 'Custom Content'
    customcontentSZ-6683: 'Custom Content'
  imagegallerySZ:
    imagegallerySZ-3581: 'Image Gallery'
    imagegallerySZ-9219: Image
  contenttabs:
    contenttabs-6250: 'Content Tabs'
  contentcubes:
    contentcubes-7850: 'Content Cubes'
  custom:
    custom-4417: 'Custom HTML'
  testimonialSZ:
    testimonialSZ-7620: Testimonials
  pricetableSZ:
    pricetableSZ-8713: 'Price Table'
  messages:
    system-messages-9330: 'System Messages'
  content:
    system-content-2446: 'Page Content'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
  logo:
    logo-6904: 'Logo / Image'
    logo-1812: 'Logo / Image'
  menu:
    menu-1531: Menu
  copyright:
    copyright-6357: Copyright
  horizontalmenu:
    horizontalmenu-4610: 'Horizontal Menu'
  totop:
    totop-2416: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-2393: 'Social Floating'
inherit:
  default:
    navigation: navigation
    footer: footer
    logo-6904: logo-9501
    menu-1531: menu-6609
    logo-1812: logo-9571
    copyright-6357: copyright-1736
    horizontalmenu-4610: horizontalmenu-9034
    totop-2416: totop-8670
    socialfloatingSZ-2393: socialfloatingSZ-2700
