name: '23'
timestamp: 1531696915
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-8132: 'Logo / Image'
    logo-9583: 'Logo / Image'
  menu:
    menu-5346: Menu
  bloglayoutSZ:
    bloglayoutSZ-1747: 'Blog layout'
  spacer:
    spacer-9755: Spacer
    spacer-7677: Spacer
  messages:
    system-messages-9284: 'System Messages'
  module:
    position-module-3449: 'articles category grouped'
    position-module-4126: latest-articles
  content:
    system-content-3365: 'Page Content'
  copyright:
    copyright-6111: Copyright
  horizontalmenu:
    horizontalmenu-3274: 'Horizontal Menu'
  totop:
    totop-3614: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-9885: 'Social Floating'
  mobile-menu:
    mobile-menu-8768: Mobile-menu
inherit:
  default:
    zenith: zenith
    navtop: navtop
    navigation: navigation
    logo-8132: logo-9501
    menu-5346: menu-6609
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    spacer-9755: spacer-2395
    mainbar: mainbar
    system-messages-9284: system-messages-2617
    position-module-3449: position-module-9693
    system-content-3365: system-content-1966
    sidebar: sidebar
    spacer-7677: spacer-4623
    position-module-4126: position-module-8967
    mainbottom: mainbottom
    footertop: footertop
    footer: footer
    logo-9583: logo-9571
    copyright-6111: copyright-1736
    horizontalmenu-3274: horizontalmenu-9034
    totop-3614: totop-8670
    socialfloatingSZ-9885: socialfloatingSZ-2700
    footerbottom: footerbottom
    nadir: nadir
    offcanvas: offcanvas
    mobile-menu-8768: mobile-menu-5697
