name: 23
timestamp: 1495993965
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  customcontentSZ:
    customcontentSZ-5013: 'Custom Content'
  custom:
    custom-7461: TITLE
    custom-1009: 'Custom HTML'
    custom-3449: TITLE
    custom-7360: 'Custom HTML'
  imagegallerySZ:
    imagegallerySZ-5839: 'Image Gallery'
    imagegallerySZ-9356: 'Image Gallery'
    imagegallerySZ-8913: 'Image Gallery'
  owlcarousel:
    owlcarousel-8932: 'Owl Carousel'
  contenttabs:
    contenttabs-9242: 'Content Tabs'
  contentcubes:
    contentcubes-5847: 'Content Cubes'
  testimonialSZ:
    testimonialSZ-6598: Testimonials
    testimonialSZ-5546: Testimonials
  pricetableSZ:
    pricetableSZ-9092: 'Price Table'
  logo:
    logo-6565: 'Logo / Image'
    logo-8132: 'Logo / Image'
  copyright:
    copyright-5570: Copyright
  horizontalmenu:
    horizontalmenu-8550: 'Horizontal Menu'
  totop:
    totop-8103: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-8669: 'Social Floating'
  mobile-menu:
    mobile-menu-5132: Mobile-menu
  menu:
    menu-5346: Menu
inherit:
  10:
    zenith: zenith
    navtop: navtop
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    mainbottom: mainbottom
    footertop: footertop
    footer: footer
    footerbottom: footerbottom
    nadir: nadir
    offcanvas: offcanvas
    customcontentSZ-5013: customcontentSZ-5107
    custom-7461: custom-8642
    imagegallerySZ-5839: imagegallerySZ-3581
    imagegallerySZ-9356: imagegallerySZ-3358
    imagegallerySZ-8913: imagegallerySZ-3171
    owlcarousel-8932: owlcarousel-2455
    contenttabs-9242: contenttabs-6250
    custom-1009: custom-1615
    contentcubes-5847: contentcubes-7850
    custom-3449: custom-4995
    testimonialSZ-6598: testimonialSZ-3654
    testimonialSZ-5546: testimonialSZ-9046
    custom-7360: custom-1476
    pricetableSZ-9092: pricetableSZ-8713
    logo-6565: logo-9571
    copyright-5570: copyright-1736
    horizontalmenu-8550: horizontalmenu-9034
    totop-8103: totop-8670
    socialfloatingSZ-8669: socialfloatingSZ-2700
    mobile-menu-5132: mobile-menu-5697
  default:
    navigation: navigation
    logo-8132: logo-9501
    menu-5346: menu-6609
