name: '21'
timestamp: 1531578855
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-8132: 'Logo / Image'
    logo-5153: 'Logo / Image'
  menu:
    menu-5346: Menu
  skillsbarSZ:
    skillsbarSZ-1000: 'Skills bar'
    skillsbarSZ-9183: 'Skills bar'
    skillsbarSZ-9795: 'Skills bar'
  spacer:
    spacer-5734: Spacer
    spacer-4771: Spacer
  messages:
    system-messages-8937: 'System Messages'
  module:
    position-module-2863: 'articles category grouped'
    position-module-9746: latest-articles
  content:
    system-content-5992: 'Page Content'
  copyright:
    copyright-6519: Copyright
  horizontalmenu:
    horizontalmenu-2348: 'Horizontal Menu'
  totop:
    totop-9082: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-1616: 'Social Floating'
  mobile-menu:
    mobile-menu-5409: Mobile-menu
inherit:
  default:
    zenith: zenith
    navtop: navtop
    navigation: navigation
    logo-8132: logo-9501
    menu-5346: menu-6609
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    spacer-5734: spacer-2395
    mainbar: mainbar
    system-messages-8937: system-messages-2617
    position-module-2863: position-module-9693
    system-content-5992: system-content-1966
    sidebar: sidebar
    spacer-4771: spacer-4623
    position-module-9746: position-module-8967
    mainbottom: mainbottom
    footertop: footertop
    footer: footer
    logo-5153: logo-9571
    copyright-6519: copyright-1736
    horizontalmenu-2348: horizontalmenu-9034
    totop-9082: totop-8670
    socialfloatingSZ-1616: socialfloatingSZ-2700
    footerbottom: footerbottom
    nadir: nadir
    offcanvas: offcanvas
    mobile-menu-5409: mobile-menu-5697
