version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
layout:
  zenith: {  }
  navtop: {  }
  navigation: {  }
  /header/:
    -
      - skillsbarSZ-1000
  /intro/:
    -
      - skillsbarSZ-9183
  /features/:
    -
      - skillsbarSZ-9795
  utility: {  }
  above: {  }
  testimonials: {  }
  expanded: {  }
  /container-main/:
    -
      -
        'aside 25': {  }
      -
        'mainbar 50': {  }
      -
        'sidebar 25': {  }
  mainbottom: {  }
  footertop: {  }
  footer: {  }
  footerbottom: {  }
  nadir: {  }
  offcanvas: {  }
structure:
  zenith:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  navtop:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  header:
    attributes:
      boxed: ''
      class: ''
      background: ''
      backgroundOverlay: ''
      backgroundAttachment: fixed
      backgroundRepeat: ''
      backgroundPosition: 'center center'
      backgroundSize: cover
  intro:
    type: section
    attributes:
      boxed: '0'
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: ''
  features:
    type: section
    attributes:
      boxed: '0'
      class: ''
      background: 'gantry-media://demos/background_blue_lines.png'
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: cover
  utility:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  testimonials:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  expanded:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  aside:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  mainbottom:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  footertop:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  footerbottom:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  nadir:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
content:
  skillsbarSZ-1000:
    title: 'Skills bar'
  skillsbarSZ-9183:
    title: 'Skills bar'
    attributes:
      enabled: 0
      style: style2
      headline: 'My awesome skills 2!'
  skillsbarSZ-9795:
    title: 'Skills bar'
    attributes:
      enabled: 0
