preset: preset1
base:
  content-margin: 0.5rem
  content-padding: 0.5rem
accent:
  color-1: '#ffeb3b'
header:
  section-preset: accent3
features:
  text-color: '#ffffff'
  link-color: '#0071bc'
utility:
  section-preset: base
testimonials:
  text-color: '#ffffff'
