name: '14'
timestamp: 1496956353
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-6904: 'Logo / Image'
    logo-9571: 'Logo / Image'
  menu:
    menu-1531: Menu
  customcontentSZ:
    customcontentSZ-5107: 'Custom Content'
  custom:
    custom-8642: TITLE
    custom-4995: TITLE
  imagegallerySZ:
    imagegallerySZ-3581: 'Image Gallery'
  contenttabs:
    contenttabs-6250: 'Content Tabs'
  contentcubes:
    contentcubes-7850: 'Content Cubes'
  testimonialSZ:
    testimonialSZ-3654: Testimonials
  pricetableSZ:
    pricetableSZ-8713: 'Price Table'
  spacer:
    spacer-spacer-4931: Spacer
    spacer-spacer-9540: Spacer
  messages:
    system-messages-9633: 'System Messages'
  content:
    system-content-7113: 'Page Content'
  copyright:
    copyright-1736: Copyright
  horizontalmenu:
    horizontalmenu-9034: 'Horizontal Menu'
  totop:
    totop-8670: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-2700: 'Social Floating'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
inherit:
  default:
    navigation: navigation
    logo-6904: logo-9501
    menu-1531: menu-6609
