version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
layout:
  /zenith/: {  }
  /navtop/: {  }
  navigation: {  }
  /header/:
    -
      - customcontentSZ-5107
  /intro/:
    -
      - custom-8642
    -
      - imagegallerySZ-3581
  /features/:
    -
      - contenttabs-6250
  /utility/: {  }
  /above/:
    -
      - contentcubes-7850
  /testimonials/:
    -
      - custom-4995
    -
      - testimonialSZ-3654
  /expanded/:
    -
      - pricetableSZ-8713
  /container-main/:
    -
      -
        'aside 25':
          -
            - spacer-spacer-4931
      -
        'mainbar 50':
          -
            - system-messages-9633
          -
            - system-content-7113
      -
        'sidebar 25':
          -
            - spacer-spacer-9540
  /mainbottom/: {  }
  /footertop/: {  }
  /footer/:
    -
      - 'logo-9571 21'
      - 'copyright-1736 26'
      - 'horizontalmenu-9034 24'
      - 'totop-8670 29'
    -
      - socialfloatingSZ-2700
  /footerbottom/: {  }
  /nadir/: {  }
  offcanvas:
    -
      - mobile-menu-5697
structure:
  zenith:
    type: section
    attributes:
      boxed: ''
  navtop:
    type: section
    attributes:
      boxed: ''
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: ''
      background: 'gantry-media://demos/gabriele-motter.jpg'
      backgroundOverlay: ''
      backgroundAttachment: fixed
      backgroundRepeat: ''
      backgroundPosition: 'center center'
      backgroundSize: cover
  intro:
    type: section
    attributes:
      boxed: '0'
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: ''
  features:
    type: section
    attributes:
      boxed: '0'
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: cover
  utility:
    type: section
    attributes:
      boxed: '0'
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
      class: ''
      background: 'gantry-media://demos/background_blue_lines.png'
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: cover
  expanded:
    type: section
    attributes:
      boxed: ''
  aside:
    attributes:
      class: ''
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  mainbottom:
    type: section
    attributes:
      boxed: ''
  footertop:
    type: section
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  footerbottom:
    type: section
    attributes:
      boxed: ''
  nadir:
    type: section
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      position: g-offcanvas-right
      class: ''
      extra: {  }
      swipe: '1'
      css3animation: '1'
content:
  customcontentSZ-5107:
    title: 'Custom Content'
    attributes:
      height: 50vh
      headline: ZEUS
      description: "<p>Free, Responsive Joomla Template</p>\n"
      link: '#'
      linktext: 'TODo Download Zeus for Free'
      link2: ''
      linktext2: ''
    block:
      variations: center
  custom-8642:
    title: TITLE
    attributes:
      html: '<h1>PARTICLES</h1>'
    block:
      variations: center
  imagegallerySZ-3581:
    title: 'Image Gallery'
    attributes:
      galleryimages:
        -
          image: 'gantry-media://demos/jump.jpg'
          effect: card
          headline: 'Image Gallery'
          description: 'Display images in a row, 4 styles available'
          link: '#'
          linktext: 'Read More'
          title: gallery
        -
          image: 'gantry-media://demos/phone.jpg'
          effect: card
          headline: 'Price Tables'
          description: 'Create Price Tables - the easy way, make them different'
          link: '#'
          linktext: 'Read More'
          title: pricetable
        -
          image: 'gantry-media://demos/jump.jpg'
          effect: card
          headline: Testimonials
          description: 'Display Testimonials blocks, 2 styles available'
          link: '#'
          linktext: 'Read More'
          title: testimonials
        -
          image: 'gantry-media://demos/phone.jpg'
          effect: none
          headline: 'Floating Icons'
          description: 'Floating social icons at left, right and bottom of the screen'
          link: '#'
          linktext: 'Read More'
          title: floating
  contenttabs-6250:
    title: 'Content Tabs'
    attributes:
      items:
        -
          content: "<ul>\n<li>Unique Particles</li>\n<li>Smart section's color style </li>\n<li>Powerful Backgrounds administration </li>\n<li>Multi-section</li>\n</ul>"
          title: Zeus
        -
          content: "<ul>\n<li>Visual Menu Editor</li>\n<li>Visual Layout Manager</li>\n<li>Unlimited Undo/Redo</li>\n<li>SCSS / LESS Support</li>\n<li>Off-Canvas Panel</li>\n<li>Particles System</li>\n<li>Twig-based Templating</li>\n<li>YAML-based Configuration</li>\n</ul>"
          title: Gantry5
        -
          content: "<ul>\n<li>Free</li>\n<li>Flexible</li>\n<li>Powerful</li>\n<li>Responsive</li>\n<li>Multi purpose template</li>\n</ul>"
          title: 'More features'
  contentcubes-7850:
    title: 'Content Cubes'
    attributes:
      items:
        -
          image: 'gantry-media://zeus/particles.png'
          imageposition: left
          label: Design
          title: 'Amazing Particles'
          content: "Create Price Tables, Image Galleries, Testimonials, Floating icons, Tabs, Carousels and other common web pages parts with ease, using drag n drop convenience. <br />\nSpeed up pages creations"
          link: '#'
          linktext: '&rarr;'
          buttonclass: ''
          buttontarget: _self
          name: Particles
        -
          image: 'gantry-media://zeus/backgrounds_playground.png'
          imageposition: right
          label: Design
          title: 'Backgrounds Playground'
          content: 'Add backgrounds images to every page or section and customize their settings just by selecting them. <br />Couldn''t be easier!'
          link: ''
          linktext: '&rarr;'
          buttonclass: ''
          buttontarget: _self
          name: backgrounds
        -
          image: 'gantry-media://zeus/smart-color-palette.png'
          imageposition: left
          label: Productivity
          title: 'Smart Color Pallete'
          content: "Select your color palette once, and voila! \nbackground, text and link colors for all sections have been updated. <br />\nChoose among predefined color combination (base, light, dark etc)  for each section. <br />\nOwesome!"
          link: ''
          linktext: '&rarr;'
          buttonclass: ''
          buttontarget: _self
          name: 'Smart pallete'
        -
          image: 'gantry-media://zeus/layout-manager.png'
          imageposition: right
          label: Productivity
          title: 'Gantry5 owesome features'
          content: "Take advantage of out-of-the-box Gantry5's amazing features: \n<ul>\n<li>Responsive design</li>\n<li>Layout Manager</li>\n<li>Unlimited Undo/Redo</li>\n<li>Visual Menu Editor</li>\n<li>SCSS / LESS Support</li>\n<li>Theme Inheritance</li>\n<li>Off-Canvas Panel</li>\n</ul>"
          link: ''
          linktext: '&rarr;'
          buttonclass: ''
          buttontarget: _self
          name: gantry
  custom-4995:
    title: TITLE
    attributes:
      html: '<h1>They just love it! </h1>'
    block:
      variations: center
  testimonialSZ-3654:
    title: Testimonials
    attributes:
      headline: ''
      testimonials:
        -
          icon: 'fa fa-quote-left fa-3x'
          quote: 'Best template ever!'
          author: Oliver
          authorattribute: 'SCSS specialist'
          image: 'gantry-media://demos/oliver_hardy.jpg'
          effect: card
          class: ''
          title: quote1
        -
          icon: 'fa fa-quote-left fa-3x'
          quote: 'szoupi has done a great Job!'
          author: Ainstein
          authorattribute: 'Front end developer'
          image: 'gantry-media://demos/einstein.jpg'
          effect: card
          class: ''
          title: quote2
        -
          icon: 'fa fa-quote-left fa-3x'
          quote: 'I use it for all my sites!'
          author: Charles
          authorattribute: 'UI Designer'
          image: 'gantry-media://demos/chaplin.jpeg'
          effect: card
          class: ''
          title: quote3
  pricetableSZ-8713:
    title: 'Price Table'
    attributes:
      mainicon: ''
      headline: 'Select Your Plan'
      pricetables:
        -
          image: ''
          icon: 'fa fa-diamond fa-3x'
          price: FREE
          description: 'You can install Zeus template unlimited times'
          line1: 'Automatic Updates'
          line2: 'Unlimited Domains'
          line3: 'Life time access'
          line4: 'Consider Donation'
          link: '#'
          linktext: 'TODO Download Now!'
          class: ''
          title: Silver
        -
          image: ''
          icon: 'fa fa-heart fa-3x'
          price: FREE
          description: 'You can install Zeus template unlimited times'
          line1: 'Unlimited Domains'
          line2: 'Automatic Updates'
          line3: 'Life time access'
          line4: 'Consider Donation'
          link: '#'
          linktext: 'TODO Download Now!'
          class: box1
          title: Gold
        -
          image: ''
          icon: 'fa fa-diamond fa-3x'
          price: FREE
          description: 'You can install Zeus template unlimited times'
          line1: 'Automatic Updates'
          line2: 'Life time access'
          line3: 'Unlimited Domains'
          line4: 'Donates are welcome'
          link: '#'
          linktext: 'TODO Download Now!'
          class: ''
          title: Bronze
    block:
      variations: center
  logo-9571:
    title: 'Logo / Image'
  horizontalmenu-9034:
    title: 'Horizontal Menu'
  totop-8670:
    title: 'To Top'
  socialfloatingSZ-2700:
    title: 'Social Floating'
