name: '15'
timestamp: 1529059647
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-8414: 'Logo / Image'
    logo-5279: 'Logo / Image'
  menu:
    menu-5350: Menu
  custom:
    custom-3590: HEADER
    custom-3975: INTRO
    custom-9130: FEATURES
    custom-5546: UTILITY
    custom-6064: ABOVE
  calltoactionSZ:
    calltoactionSZ-7996: 'Call to action'
    calltoactionSZ-2971: 'Call to action'
    calltoactionSZ-9704: 'Call to action'
    calltoactionSZ-3107: 'Call to action'
    calltoactionSZ-2500: 'Call to action'
  spacer:
    spacer-2711: Spacer
    spacer-1722: Spacer
  messages:
    system-messages-7759: 'System Messages'
  module:
    position-module-2964: 'articles category grouped'
    position-module-3048: latest-articles
  content:
    system-content-9383: 'Page Content'
  copyright:
    copyright-2445: Copyright
  horizontalmenu:
    horizontalmenu-9783: 'Horizontal Menu'
  totop:
    totop-5555: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-6898: 'Social Floating'
  mobile-menu:
    mobile-menu-5155: Mobile-menu
inherit:
  default:
    zenith: zenith
    navtop: navtop
    navigation: navigation
    logo-8414: logo-9501
    menu-5350: menu-6609
    testimonials: testimonials
    expanded: expanded
    aside: aside
    spacer-2711: spacer-2395
    mainbar: mainbar
    system-messages-7759: system-messages-2617
    position-module-2964: position-module-9693
    system-content-9383: system-content-1966
    sidebar: sidebar
    spacer-1722: spacer-4623
    position-module-3048: position-module-8967
    mainbottom: mainbottom
    footertop: footertop
    footer: footer
    logo-5279: logo-9571
    copyright-2445: copyright-1736
    horizontalmenu-9783: horizontalmenu-9034
    totop-5555: totop-8670
    socialfloatingSZ-6898: socialfloatingSZ-2700
    footerbottom: footerbottom
    nadir: nadir
    offcanvas: offcanvas
    mobile-menu-5155: mobile-menu-5697
