version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
layout:
  zenith: {  }
  navtop: {  }
  navigation: {  }
  /header/:
    -
      - custom-3590
    -
      - calltoactionSZ-7996
    -
      - timelineSZ-7602
  /intro/:
    -
      - custom-3975
    -
      - calltoactionSZ-2971
  /features/:
    -
      - custom-9130
    -
      - calltoactionSZ-9704
  /utility/:
    -
      - custom-5546
    -
      - calltoactionSZ-3107
  /above/:
    -
      - custom-6064
    -
      - calltoactionSZ-2500
  testimonials: {  }
  expanded: {  }
  /container-main/:
    -
      -
        'aside 25': {  }
      -
        'mainbar 50': {  }
      -
        'sidebar 25': {  }
  mainbottom: {  }
  footertop: {  }
  footer: {  }
  footerbottom: {  }
  nadir: {  }
  offcanvas: {  }
structure:
  zenith:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  navtop:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  header:
    attributes:
      boxed: ''
      class: ''
      background: ''
      backgroundOverlay: ''
      backgroundAttachment: fixed
      backgroundRepeat: ''
      backgroundPosition: 'center center'
      backgroundSize: cover
  intro:
    type: section
    attributes:
      boxed: '0'
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: ''
  features:
    type: section
    attributes:
      boxed: '0'
      class: ''
      background: 'gantry-media://demos/background_blue_lines.png'
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: cover
  utility:
    type: section
    attributes:
      boxed: '0'
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: ''
  above:
    type: section
    attributes:
      boxed: ''
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: ''
  testimonials:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  expanded:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  aside:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  mainbottom:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  footertop:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  footerbottom:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  nadir:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
content:
  custom-3590:
    title: HEADER
    attributes:
      html: '<h1>HEADER BASE</h1>'
  calltoactionSZ-7996:
    title: 'Call to action'
  timelineSZ-7602:
    title: Timeline
    attributes:
      headline: 'Timeline particle'
      description: 'events of the world '
      events:
        -
          icon: 'fa fa-calendar-times-o'
          date: '2018'
          subtitle: 'this is a subtitle'
          description: 'fafd adf asd;f asd fasd fasd f'
          position: left
          class: ''
          title: 'New item'
        -
          icon: 'fa fa-calendar-times-o'
          date: '2020'
          subtitle: hh
          description: 'asdljkf a;sdf jal;ksdjf as;ldkfj asdlkfj asd;lkj '
          position: right
          class: ''
          title: 'New item'
  custom-3975:
    title: INTRO
    attributes:
      html: '<h1>INTRO PRIMARY</h1>'
  calltoactionSZ-2971:
    title: 'Call to action'
  custom-9130:
    title: FEATURES
    attributes:
      html: '<h1>FEATURES CONTRAST ACCENT 1</h1>'
  calltoactionSZ-9704:
    title: 'Call to action'
  custom-5546:
    title: UTILITY
    attributes:
      html: '<h1>UTILITY LIGHT ACCENT 2</h1>'
  calltoactionSZ-3107:
    title: 'Call to action'
  custom-6064:
    title: ABOVE
    attributes:
      html: '<h1>ABOVE DARK ACCENT 3</h1>'
  calltoactionSZ-2500:
    title: 'Call to action'
    attributes:
      link2: ''
      linktext2: ''
