preset: preset1
header:
  section-preset: base
intro:
  section-preset: primary
features:
  section-preset: accent1
utility:
  section-preset: accent2
above:
  section-preset: accent3
testimonials:
  section-preset: accent3
sectionsdim:
  zenith-padding: 0rem
