preset: preset1
base:
  content-margin: 0.5rem
  content-padding: 0.5rem
intro:
  section-preset: accent3
  background: '#ffffff'
features:
  section-preset: base
utility:
  section-preset: accent3
testimonials:
  text-color: '#ffffff'
