name: 18
timestamp: 1528234785
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions:
  sidebar: sidebar
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9958: 'Logo / Image'
    logo-3070: 'Logo / Image'
  menu:
    menu-9003: Menu
  customcontentSZ:
    customcontentSZ-9921: 'Custom Content'
  spacer:
    spacer-2678: Spacer
    spacer-8820: Spacer
  messages:
    system-messages-1808: 'System Messages'
  content:
    system-content-5835: 'Page Content'
  position:
    position-position-3039: sidebar
  copyright:
    copyright-1874: Copyright
  horizontalmenu:
    horizontalmenu-7528: 'Horizontal Menu'
  totop:
    totop-3105: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-8802: 'Social Floating'
  mobile-menu:
    mobile-menu-4333: Mobile-menu
inherit:
  default:
    zenith: zenith
    navtop: navtop
    navigation: navigation
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    mainbottom: mainbottom
    footertop: footertop
    footer: footer
    footerbottom: footerbottom
    nadir: nadir
    offcanvas: offcanvas
    logo-9958: logo-9501
    menu-9003: menu-6609
    spacer-2678: spacer-2395
    system-messages-1808: system-messages-2617
    system-content-5835: system-content-1966
    spacer-8820: spacer-4623
    position-position-3039: position-position-3512
    logo-3070: logo-9571
    copyright-1874: copyright-1736
    horizontalmenu-7528: horizontalmenu-9034
    totop-3105: totop-8670
    socialfloatingSZ-8802: socialfloatingSZ-2700
    mobile-menu-4333: mobile-menu-5697
