name: '18'
timestamp: 1530793043
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-3208: 'Logo / Image'
    logo-2093: 'Logo / Image'
  menu:
    menu-4714: Menu
  portfolioSZ:
    portfolioSZ-3657: Portfolio
  spacer:
    spacer-7698: Spacer
    spacer-5924: Spacer
  messages:
    system-messages-7494: 'System Messages'
  module:
    position-module-3184: 'articles category grouped'
    position-module-1765: latest-articles
  content:
    system-content-2151: 'Page Content'
  copyright:
    copyright-5363: Copyright
  horizontalmenu:
    horizontalmenu-3230: 'Horizontal Menu'
  totop:
    totop-5667: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-2797: 'Social Floating'
  mobile-menu:
    mobile-menu-1515: Mobile-menu
inherit:
  default:
    zenith: zenith
    navtop: navtop
    navigation: navigation
    logo-3208: logo-9501
    menu-4714: menu-6609
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    spacer-7698: spacer-2395
    mainbar: mainbar
    system-messages-7494: system-messages-2617
    position-module-3184: position-module-9693
    system-content-2151: system-content-1966
    sidebar: sidebar
    spacer-5924: spacer-4623
    position-module-1765: position-module-8967
    mainbottom: mainbottom
    footertop: footertop
    footer: footer
    logo-2093: logo-9571
    copyright-5363: copyright-1736
    horizontalmenu-3230: horizontalmenu-9034
    totop-5667: totop-8670
    socialfloatingSZ-2797: socialfloatingSZ-2700
    footerbottom: footerbottom
    nadir: nadir
    offcanvas: offcanvas
    mobile-menu-1515: mobile-menu-5697
