name: '18'
timestamp: 1529357323
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  calltoactionSZ:
    calltoactionSZ-9676: 'Call to action'
    calltoactionSZ-5285: 'Call to action'
    calltoactionSZ-8266: 'Call to action'
    calltoactionSZ-2363: 'Call to action'
    calltoactionSZ-9958: 'Call to action'
    calltoactionSZ-6371: 'Call to action'
    calltoactionSZ-5747: 'Call to action'
    calltoactionSZ-5315: 'Call to action'
    calltoactionSZ-7644: 'Call to action'
    calltoactionSZ-7298: 'Call to action'
    calltoactionSZ-6589: 'Call to action'
    calltoactionSZ-5752: 'Call to action'
    calltoactionSZ-5990: 'Call to action'
    calltoactionSZ-5585: 'Call to action'
    calltoactionSZ-8705: 'Call to action'
    calltoactionSZ-4495: 'Call to action'
    calltoactionSZ-3465: 'Call to action'
  custom:
    custom-9493: 'Custom HTML'
  logo:
    logo-9501: 'Logo / Image'
    logo-9571: 'Logo / Image'
  menu:
    menu-6609: Menu
  spacer:
    spacer-2395: Spacer
    spacer-4623: Spacer
  messages:
    system-messages-2617: 'System Messages'
  content:
    system-content-1966: 'Page Content'
  copyright:
    copyright-1736: Copyright
  horizontalmenu:
    horizontalmenu-9034: 'Horizontal Menu'
  totop:
    totop-8670: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-2700: 'Social Floating'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
inherit: {  }
