preset: preset1
font:
  family-title: 'Lato, Helvetica, Tahoma, Geneva, Arial, sans-serif'
header:
  section-preset: base
intro:
  section-preset: primary
features:
  section-preset: accent1
utility:
  section-preset: accent2
above:
  section-preset: accent3
  text-color: '#212121'
