name: 24
timestamp: 1495993965
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490038588
positions: {  }
sections:
  zenith: Zenith
  navtop: Navtop
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  mainbottom: Mainbottom
  footertop: Footertop
  footerbottom: Footerbottom
  nadir: Nadir
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  customcontentSZ:
    customcontentSZ-1908: 'Custom Content'
  custom:
    custom-8719: TITLE
    custom-8723: 'Custom HTML'
    custom-2123: TITLE
    custom-4878: 'Custom HTML'
  imagegallerySZ:
    imagegallerySZ-1290: 'Image Gallery'
    imagegallerySZ-8017: 'Image Gallery'
    imagegallerySZ-2449: 'Image Gallery'
  owlcarousel:
    owlcarousel-7794: 'Owl Carousel'
  contenttabs:
    contenttabs-2011: 'Content Tabs'
  contentcubes:
    contentcubes-2084: 'Content Cubes'
  testimonialSZ:
    testimonialSZ-2156: Testimonials
    testimonialSZ-8956: Testimonials
  pricetableSZ:
    pricetableSZ-2599: 'Price Table'
  logo:
    logo-1976: 'Logo / Image'
    logo-8132: 'Logo / Image'
  copyright:
    copyright-3130: Copyright
  horizontalmenu:
    horizontalmenu-6821: 'Horizontal Menu'
  totop:
    totop-8886: 'To Top'
  socialfloatingSZ:
    socialfloatingSZ-7591: 'Social Floating'
  mobile-menu:
    mobile-menu-8779: Mobile-menu
  menu:
    menu-5346: Menu
inherit:
  10:
    zenith: zenith
    navtop: navtop
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    mainbottom: mainbottom
    footertop: footertop
    footer: footer
    footerbottom: footerbottom
    nadir: nadir
    offcanvas: offcanvas
    customcontentSZ-1908: customcontentSZ-5107
    custom-8719: custom-8642
    imagegallerySZ-1290: imagegallerySZ-3581
    imagegallerySZ-8017: imagegallerySZ-3358
    imagegallerySZ-2449: imagegallerySZ-3171
    owlcarousel-7794: owlcarousel-2455
    contenttabs-2011: contenttabs-6250
    custom-8723: custom-1615
    contentcubes-2084: contentcubes-7850
    custom-2123: custom-4995
    testimonialSZ-2156: testimonialSZ-3654
    testimonialSZ-8956: testimonialSZ-9046
    custom-4878: custom-1476
    pricetableSZ-2599: pricetableSZ-8713
    logo-1976: logo-9571
    copyright-3130: copyright-1736
    horizontalmenu-6821: horizontalmenu-9034
    totop-8886: totop-8670
    socialfloatingSZ-7591: socialfloatingSZ-2700
    mobile-menu-8779: mobile-menu-5697
  default:
    navigation: navigation
    logo-8132: logo-9501
    menu-5346: menu-6609
