preset: preset3
base:
  dominant-color: '#8f734a'
  text-color: '#212121'
  background: '#ffffff'
  content-margin: 0.5rem
  content-padding: 0.5rem
accent:
  color-1: '#893040'
  color-2: '#d1b379'
  color-3: '#314159'
zenith:
  section-preset: disabled
  link-color: '#8f734a'
navtop:
  section-preset: accent2
  link-color: '#8f734a'
navigation:
  background: '#8f734a'
header:
  text-color: '#212121'
  link-color: '#8f734a'
intro:
  section-preset: accent2
  link-color: '#8f734a'
features:
  section-preset: accent2
  text-color: '#ffffff'
  link-color: '#8f734a'
utility:
  link-color: '#8f734a'
above:
  link-color: '#8f734a'
testimonials:
  link-color: '#8f734a'
expanded:
  section-preset: accent2
  text-color: '#ffffff'
  link-color: '#8f734a'
mainbottom:
  section-preset: accent2
  link-color: '#8f734a'
footertop:
  section-preset: accent2
  link-color: '#8f734a'
footer:
  link-color: '#d1b379'
footerbottom:
  section-preset: accent2
  link-color: '#8f734a'
nadir:
  text-color: '#ffffff'
  link-color: '#8f734a'
offcanvas:
  background: '#8f734a'
  toggle-color: '#ffffff'
